### ISSUE TITLE
citywar

### ISSUE THREAD

**Issue by titanicoxd** [brunominervino/tfs_systems#3]
Porque quando usa o citywar não funciona os frags da warsystem?
Invita outra guild para war normalmente, dai usa o citywar como anti-entrosa.
O score da war system fica 0x0
Tem como arrumar pra score funcionar e o frags da citywar também?

**Comment by brunominervino** [comment]
Muito obrigado pelo feedback.
Porém esses sistemas foram desenvolvidos sem os seus devidos testes, e disponibilizados para dar uma ideia, um rumo no caminho certo.
Caso alguém queira realizar as correções, eu dou total apoio, porém, eu não posso por falta de tempo.

Espero que entenda!
